### ISSUE TITLE
PS Core support?

### ISSUE THREAD

**Issue by chlsmith** [azsk/DevOpsKit-docs#126]
Showing only desktop on the screenshot and I tried with PS Core and got a lot of errors.

**Comment by NitroAMD** [comment]
Same here:

Linux:
PS /home/user1> Install-Module AzSK

Untrusted repository
You are installing the modules from an untrusted repository. If you trust this repository, change its InstallationPolicy value by
running the Set-PSRepository cmdlet. Are you sure you want to install the modules from 'PSGallery'?
[Y] Yes  [A] Yes to All  [N] No  [L] No to All  [S] Suspend  [?] Help (default is "N"): A
PackageManagement\Install-Package : The member 'TypesToProcess' in the module manifest is not valid: Cannot find path '/tmp/152982406
6/Azure.Storage.4.5.0/.\Microsoft.WindowsAzure.Commands.Storage.Types.ps1xml' because it does not exist.. Verify that a valid value i
s specified for this field in the '/tmp/1529824066/Azure.Storage.4.5.0/Azure.Storage.psd1' file.
At /opt/microsoft/powershell/6/Modules/PowerShellGet/PSModule.psm1:9491 char:21
+ ...          $null = PackageManagement\Install-Package @PSBoundParameters
+                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : ResourceUnavailable: (/tmp/1529824066...re.Storage.psd1:String) [Install-Package], Exception
+ FullyQualifiedErrorId : Modules_InvalidManifest,Microsoft.PowerShell.Commands.TestModuleManifestCommand,Microsoft.PowerShell.Packag
eManagement.Cmdlets.InstallPackage

PS /home/user1> Get-AzSKSubscriptionSecurityStatus
Get-AzSKSubscriptionSecurityStatus : The term 'Get-AzSKSubscriptionSecurityStatus' is not recognized as the name of a cmdlet, functio
n, script file, or operable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ Get-AzSKSubscriptionSecurityStatus
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : ObjectNotFound: (Get-AzSKSubscriptionSecurityStatus:String) [], CommandNotFoundException
+ FullyQualifiedErrorId : CommandNotFoundException

#######

Name                           Value
----                           -----
PSVersion                      6.1.0
PSEdition                      Core
GitCommitId                    6.1.0
OS                             Linux 4.4.0-17763-Microsoft #55-Microsoft Sat Oct 06 18:05:00 PST 2018
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0


Azure Cloud Shell:
PS Azure:\> Install-Module AzSK -Scope CurrentUser -AllowClobber -Force
PackageManagement\Install-Package : Package 'AzureRM.profile' failed to be installed because: End of Central Directory record could not be found.At /opt/microsoft/powershell/6/Modules/PowerShellGet/PSModule.psm1:9491 char:21+ ...          $null = PackageManagement\Install-Package @PSBoundParameters+                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~+ CategoryInfo          : InvalidResult: (AzureRM.profile:String) [Install-Package], Exception+ FullyQualifiedErrorId : Package '{0}' failed to be installed because: {1},Microsoft.PowerShell.PackageManagement.Cmdlets.InstallPackageAzure:/

PS Azure:\> $psversiontable

Name                           Value
----                           -----
PSVersion                      6.1.0
PSEdition                      Core
GitCommitId                    6.1.0
OS                             Linux 4.15.0-1023-azure #24~16.04.1-Ubuntu SMP Wed Aug 29 12:54:36 UTC 2018
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

**Comment by VishalHaibatpure** [comment]
Currently AzSK supported on PSVersion 5.x. AzSK internally uses AzureRM modules and all the modules/commands does not supports as part of PS Core (x Platform). 
We have this as part of backlog to support PSCore

**Comment by pjbgf** [comment]
I would be great if that information was central stage on the documentation.
